#!/usr/bin/env python3
"""
setup_wizard.py — Interactive configuration wizard
===================================================

Walks you through creating python/config/config.yaml step-by-step.
Supports both exchange API keys and environment variables.

Run directly:
    python python/setup_wizard.py

Or via the main launcher:
    python arb.py wizard
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# ── Config file paths ────────────────────────────────────────────────────────
THIS_DIR   = Path(__file__).parent.resolve()
CONFIG_DIR = THIS_DIR / "config"
CONFIG_OUT = CONFIG_DIR / "config.yaml"
ENV_OUT    = THIS_DIR.parent / ".env"  # repo root .env


# ── Rich helpers ──────────────────────────────────────────────────────────────

def _require_rich():
    try:
        import rich  # noqa: F401
    except ImportError:
        print("\n  rich not installed — run: pip install rich\n")
        sys.exit(1)


def _header(console, title: str):
    from rich.panel import Panel
    console.print(Panel(f"[bold cyan]{title}[/]", border_style="cyan"))


def _ask(console, prompt: str, default: str = "", password: bool = False) -> str:
    from rich.prompt import Prompt
    return Prompt.ask(f"  {prompt}", default=default, password=password)


def _confirm(console, prompt: str, default: bool = False) -> bool:
    from rich.prompt import Confirm
    return Confirm.ask(f"  {prompt}", default=default)


# ── Exchange configurator ─────────────────────────────────────────────────────

EXCHANGES = [
    ("binance",  "Binance",          False),
    ("kraken",   "Kraken",           False),
    ("coinbase", "Coinbase",         False),
    ("bybit",    "Bybit",            False),
    ("kucoin",   "KuCoin",           True),   # needs passphrase
    ("okx",      "OKX",              True),   # needs passphrase
]

TESTNET_LINKS = {
    "binance":  "https://testnet.binance.vision",
    "bybit":    "https://testnet.bybit.com",
    "coinbase": "(no public testnet — use dry_run)",
    "kraken":   "(no public testnet — use dry_run)",
    "kucoin":   "(no public testnet — use dry_run)",
    "okx":      "https://www.okx.com/testnet",
}


def _configure_exchange(console, name: str, label: str, needs_passphrase: bool) -> dict | None:
    console.print(f"\n  [bold]{label}[/]")
    if not _confirm(console, f"Enable {label}?", default=False):
        return None

    testnet = TESTNET_LINKS.get(name, "")
    if testnet and not testnet.startswith("("):
        console.print(f"    [dim]Testnet: {testnet}[/]")

    api_key    = _ask(console, f"{label} API key",    password=True)
    api_secret = _ask(console, f"{label} API secret", password=True)
    passphrase = ""
    if needs_passphrase:
        passphrase = _ask(console, f"{label} passphrase", password=True)
    sandbox = _confirm(console, f"Use {label} sandbox/testnet?", default=True)

    return {
        "api_key":    api_key    or f"YOUR_{name.upper()}_API_KEY",
        "api_secret": api_secret or f"YOUR_{name.upper()}_API_SECRET",
        "passphrase": passphrase or (f"YOUR_{name.upper()}_PASSPHRASE" if needs_passphrase else ""),
        "sandbox":    sandbox,
        "needs_passphrase": needs_passphrase,
    }


# ── Config writer ─────────────────────────────────────────────────────────────

def _write_config(exchanges: dict, arb: dict, tri: dict, ai: dict) -> None:
    lines = [
        "# Arbitrage Bots — config.yaml",
        "# Generated by setup_wizard.py",
        "# NEVER commit this file with real API keys!\n",
        "exchanges:",
    ]
    for name, cfg in exchanges.items():
        if cfg is None:
            continue
        lines.append(f"  {name}:")
        lines.append(f'    api_key:    "{cfg["api_key"]}"')
        lines.append(f'    api_secret: "{cfg["api_secret"]}"')
        if cfg.get("needs_passphrase") and cfg.get("passphrase"):
            lines.append(f'    passphrase: "{cfg["passphrase"]}"')
        lines.append(f'    sandbox:    {"true" if cfg["sandbox"] else "false"}')
        lines.append("")

    lines += [
        "arbitrage:",
        "  symbols:",
        '    - "BTC/USDT"',
        '    - "ETH/USDT"',
        '    - "SOL/USDT"',
        '    - "XRP/USDT"',
        f'  min_profit_pct:        {arb["min_profit"]}',
        f'  max_trade_size_usdt:   {arb["max_size"]}',
        f'  poll_interval_seconds: {arb["poll"]}',
        f'  dry_run:               {"true" if arb["dry_run"] else "false"}',
        "",
        "triangular:",
        f'  exchange:      "{tri["exchange"]}"',
        '  base_currency: "USDT"',
        f'  min_profit_pct: {tri["min_profit"]}',
        f'  dry_run:       {"true" if tri["dry_run"] else "false"}',
        "",
        "ai:",
        "  history_candles:    500",
        "  feature_window:      20",
        f'  prediction_threshold: {ai["threshold"]}',
        "  rl_episode_steps:   200",
        '  model_dir:          "models/"',
        f'  dry_run:            {"true" if ai["dry_run"] else "false"}',
        "",
        "logging:",
        '  level:    "INFO"',
        '  log_file: "arb_bot.log"',
    ]

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    CONFIG_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_env(exchanges: dict) -> None:
    """Write an .env file with all API keys as environment variables."""
    lines = [
        "# .env — API keys as environment variables",
        "# Generated by setup_wizard.py",
        "# NEVER commit this file!\n",
    ]
    for name, cfg in exchanges.items():
        if cfg is None:
            continue
        n = name.upper()
        lines.append(f'{n}_API_KEY="{cfg["api_key"]}"')
        lines.append(f'{n}_API_SECRET="{cfg["api_secret"]}"')
        if cfg.get("needs_passphrase") and cfg.get("passphrase"):
            lines.append(f'{n}_PASSPHRASE="{cfg["passphrase"]}"')
        lines.append("")
    ENV_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ── Main wizard ───────────────────────────────────────────────────────────────

def run():
    _require_rich()
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Prompt, Confirm

    console = Console()
    console.print()
    _header(console,
            "⚙️  Arbitrage Bots — Setup Wizard\n"
            "[dim]This wizard creates python/config/config.yaml[/]")

    console.print(
        "\n  [yellow]⚠  API keys are stored locally only.[/]\n"
        "  [yellow]    Never share config.yaml or .env with anyone.[/]\n"
        "  [green]  Tip: Leave all fields blank to keep the placeholder values.[/]\n"
        "  [green]       You can re-run this wizard any time to update settings.[/]\n"
    )

    # ── Exchanges ──────────────────────────────────────────────────────────────
    _header(console, "Step 1 — Exchange API Keys")
    console.print("  [dim]You only need to configure exchanges you actually want to use.[/]\n"
                  "  [dim]For simulation/backtesting, skip all of these.[/]\n")

    exchange_configs: dict = {}
    for name, label, needs_pp in EXCHANGES:
        cfg = _configure_exchange(console, name, label, needs_pp)
        exchange_configs[name] = cfg

    enabled = [k for k, v in exchange_configs.items() if v is not None]
    if not enabled:
        console.print("\n  [yellow]No exchanges configured — all bots will run in simulation/dry-run mode.[/]")

    # ── Arbitrage settings ─────────────────────────────────────────────────────
    console.print()
    _header(console, "Step 2 — Arbitrage Settings")

    min_profit = _ask(console, "Minimum profit % before trading", default="0.5")
    max_size   = _ask(console, "Maximum trade size (USDT)",       default="100")
    poll       = _ask(console, "Price polling interval (seconds)", default="5")
    dry_run    = _confirm(console, "Run in dry_run mode? (recommended until tested)", default=True)

    arb_cfg = {
        "min_profit": min_profit,
        "max_size":   max_size,
        "poll":       poll,
        "dry_run":    dry_run,
    }

    # ── Triangular settings ────────────────────────────────────────────────────
    console.print()
    _header(console, "Step 3 — Triangular Arbitrage Settings")

    tri_exchange   = _ask(console, "Exchange to run triangular arb on", default="binance")
    tri_min_profit = _ask(console, "Minimum profit % for triangular arb", default="0.3")
    tri_dry_run    = _confirm(console, "Triangular dry_run?", default=True)

    tri_cfg = {
        "exchange":   tri_exchange,
        "min_profit": tri_min_profit,
        "dry_run":    tri_dry_run,
    }

    # ── AI settings ───────────────────────────────────────────────────────────
    console.print()
    _header(console, "Step 4 — AI Bot Settings")

    ai_threshold = _ask(console, "Prediction threshold (% spread AI must predict)", default="0.4")
    ai_dry_run   = _confirm(console, "AI bot dry_run?", default=True)

    ai_cfg = {
        "threshold": ai_threshold,
        "dry_run":   ai_dry_run,
    }

    # ── Write files ────────────────────────────────────────────────────────────
    console.print()
    _header(console, "Step 5 — Saving Configuration")

    overwrite = True
    if CONFIG_OUT.exists():
        overwrite = _confirm(console, f"Overwrite existing config.yaml?", default=True)

    # Warn if config.yaml is somehow not in .gitignore
    gitignore = THIS_DIR.parent / ".gitignore"
    if gitignore.exists():
        gi_text = gitignore.read_text(encoding="utf-8")
        if "config.yaml" not in gi_text:
            console.print(
                "  [red]⚠  WARNING: config.yaml does not appear to be in .gitignore![/]\n"
                "     Add 'python/config/config.yaml' to .gitignore before committing."
            )

    if overwrite:
        _write_config(exchange_configs, arb_cfg, tri_cfg, ai_cfg)
        console.print(f"  [green]✔  Saved:[/] {CONFIG_OUT}")

        write_env = _confirm(console, "Also write .env file (API keys as env vars)?", default=True)
        if write_env:
            _write_env(exchange_configs)
            console.print(f"  [green]✔  Saved:[/] {ENV_OUT}")
    else:
        console.print("  [yellow]Skipped — config.yaml not modified.[/]")

    # ── Summary ────────────────────────────────────────────────────────────────
    console.print()
    console.print(
        "[bold green]  ✔  Wizard complete![/]\n\n"
        "  Next steps:\n\n"
    )
    if not dry_run:
        console.print("  [bold red]  ⚠  LIVE MODE ENABLED — trades will use real money![/]")
    console.print(
        "    python arb.py          [dim]— open the launcher menu[/]\n\n"
        "  [dim]To run the simulator (no keys needed):[/]\n"
        "    python arb.py simulate\n"
    )


if __name__ == "__main__":
    run()
